all:

	g++ gen_prm.cpp gen_prm.h  gen_bits.cpp gen_bits.h  pow_number.cpp pow_number.h get_number_bits.h get_number_bits.cpp rsa.cpp rsa.h rsa_file_crypt.h rsa_file_crypt.cpp  test.cpp ../include/gmpxx.h -L ../lib/libgmpxx.a ../lib/libgmp.a -o ../bin/gen_prm


