all:

	g++ gen_prm.cpp gen_prm.h  gen_bits.cpp gen_bits.h get_number_bits.cpp get_number_bits.h pow_number.cpp pow_number.h rsa.cpp rsa.h  test.cpp ../include/gmpxx.h -L ../lib/libgmpxx.a ../lib/libgmp.a -o ../bin/gen_prm


